#!/bin/bash 

echo Now assembling, compiling, and linking your kernel...
nasm -f aout -o start.o start.asm

# remember this spot here: we will add `gcc' commands here to compile C sources


# this links all your files.  remember that as you add *.o files, you need to
# add them after start.o.  if you don't add them at all, they won't be in your
# kernel!
ld -T link.ld -o kernel.bin start.o

gcc -Wall -O -fstrength-reduce -fomit-frame-pointer -finline-functions -nostdinc \
    -fno-builtin -I./include -c -o main.o main.c
echo Done!
